apply plugin: 'java'
apply plugin: 'kotlin'

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation gradleApi()
    implementation project(':matrix-commons')
    implementation 'org.ow2.asm:asm:9.7.1'
    implementation 'org.ow2.asm:asm-commons:9.7.1'
    implementation 'org.ow2.asm:asm-util:9.7.1'
    implementation "com.android.tools.build:gradle:$gradle.AGP_VERSION"
    implementation 'com.android.tools:common:31.0.1'
    implementation 'com.google.code.gson:gson:2.9.1'
    implementation project(':matrix-arscutil')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${gradle.KOTLIN_VERSION}"
}

processResources {
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
}

sourceSets {
    main {
        java {
            srcDir "../matrix-gradle-plugin/src/main/java"
        }

        resources {
            srcDir '../matrix-gradle-plugin/src/main/resources'
        }
    }
}

version rootProject.ext.VERSION_NAME
group rootProject.ext.GROUP

if("External" == rootProject.ext.PUBLISH_CHANNEL) {
    apply from: rootProject.file('gradle/java-publish.gradle')
}
else {
    apply from: rootProject.file('gradle/WeChatPublish.gradle')
    wechatPublish {
        artifactId = POM_ARTIFACT_ID
    }
}